name: Auto Assign to Project(s)

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
env:
  GITHUB_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues to project 4
      uses: srggrs/assign-one-project-github-action@1.2.1
      project: 'https://github.com/users/capri1989/projects/4'
      column_name: 'No Status'

